export const preloadList: string[] = [
  "ana-avatar.png",
  "any.svg",               "arrow-down.svg",
  "arrow-up.svg",          "ashe-avatar.png",
  "ball-avatar.png",       "baptiste-avatar.png",
  "bastion-avatar.png",    "brigitte-avatar.png",
  "cassidy-avatar.png",    "doomfist-avatar.png",
  "dps.svg",               "dva-avatar.png",
  "echo-avatar.png",       "genji-avatar.png",
  "hanzo-avatar.png",      "junkrat-avatar.png",
  "kiriko-avatar.png",     "lucio-avatar.png",
  "mei-avatar.png",        "mercy-avatar.png",
  "moira-avatar.png",      "orisa-avatar.png",
  "pharah-avatar.png",
  "queen-avatar.png",      "reaper-avatar.png",
  "reinhardt-avatar.png",  "roadhog-avatar.png",
  "settings.svg",          "sigma-avatar.png",
  "sojourn-avatar.png",    "soldier-avatar.png",
  "sombra-avatar.png",     "support.svg",
  "symmetra-avatar.png",   "tank.svg",
  "torbjorn-avatar.png",   "tracer-avatar.png",
  "widowmaker-avatar.png", "winston-avatar.png",
  "zarya-avatar.png",      "zenyatta-avatar.png"
]

